### ISSUE TITLE
Clicking things doesn't work.

### ISSUE THREAD

**Issue by cauebs** [setzer22/blackjack#1]
First, awesome project. Congrats.

When I click any UI elements, I get the mouse down style (e.g. on buttons) but it has no effect. Pressing `Enter` works, if the element is selected (iterating over them with `Tab` works).

I'm on Sway (wlroots-based Wayland compositor).

**Comment by setzer22** [comment]
Thanks for reporting! 

I had been bugged about click detection being slightly inconsistent on my machine, but it sounds worse in your case as you weren't able to click at all. That leads me to think it may be related to framerate. It looks like capping the application to render at 60Hz made click detection completely consistent on my end.

Can you try after my last commit (890dd1b) and see if that works on your end?

**Comment by cauebs** [comment]
Yes, it does! :)
