### ISSUE TITLE
Panic on start when loading texture

### ISSUE THREAD

**Issue by UE2020** [setzer22/blackjack#20]
I cloned the respository, compiled blackjack using `cargo build --release` and attempted to run it. I got this error:

```rs
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'loading texture E8DEE1_B5A6AA_CCBCC1_C4BBBC: Unsupported(UnsupportedError { format: Unknown, kind: Format(Unknown) })', src/rendergraph/face_routine.rs:133:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This may be an issue with wgpu, but I highly doubt it as I've used & written a lot of other wgpu applications which don't suffer from any issues.

System information:

OS: Linux
GPU: Intel UHD Graphics 620

**Comment by setzer22** [comment]
Oh, I think I know what's going on. I just enabled git lfs to store the textures, so if you didn't fetch LFS files you're trying to read an LFS "pointer" as a texture.

Can you try looking at the images in the `assets` folder? If you see them as text files, that's exactly the issue.

To fix it, try running:
```
git lfs install
git lfs fetch --all
git lfs pull
```

After that, everything should work normally :smile: 

I'm going to update the instructions on the README with this.

**Comment by UE2020** [comment]
I ran the `git lfs` commands and recompiled. Everything works now!

**Comment by setzer22** [comment]
Thanks for reporting this! :smile:
