### ISSUE TITLE
Godot plugin no longer works with Godot 3.5

### ISSUE THREAD

**Issue by novhack** [setzer22/blackjack#39]
Godot 3.5 was released today and it seems the way how the plugin exported properties to Godot inspector no longer works or something else changed. Jack Property, Show Gui and Material Slot no longer show up. With the version 3.4.5 it works fine and all properties are shown. I tried it with the plugin and libblackjack_godot.so compiled from the latest main on Arch Linux.

**Comment by novhack** [comment]
I discussed these errors with guys from godot-rust and it seems some issues will be addressed with gdnative crate 0.10.1. I tried to compile the plugin with the latest git version of godot-rust but now it crashes the editor when I try to add the blackjackjack node into a scene tree.

**Comment by setzer22** [comment]
Hey! Thanks for reporting. I haven't yet had time to test Godot 3.5 with blackjack. I'll have a look at this soon :+1:

>  the way how the plugin exported properties to Godot inspector no longer works or something else changed

> I discussed these errors with guys from godot-rust and it seems some issues will be addressed with gdnative crate 0.10.1

The part of the plugin handling the exported properties is written in GDScript, so if that broke maybe it's some change in Godot's internal representation of `get_property_list`. I will see what I can to :thinking:

**Comment by novhack** [comment]
A new version of gdnative crate 0.11 has been released yesterday. It should support Godot 3.5 however it drops support for older Godot versions.

**Comment by setzer22** [comment]
Still aware of this. If there are no major blockers, I'm planning to push a fix for this in my next PR :+1:

**Comment by setzer22** [comment]
This was fixed in the (still unmerged) commit 646a8b56e1. Still needs a bit more testing, so I will keep this open until I merge the PR (hopefully soon! :tada:)

**Comment by setzer22** [comment]
This will be fixed by #62 :+1:
