### ISSUE TITLE
Impossible to zoom and hard to trigger click

### ISSUE THREAD

**Issue by Kerollmops** [setzer22/blackjack#7]
I tried blackjack on my MacBook Pro 13' M1 and found out that it was impossible to zoom by using the "roulette wheel" i.e. on my trackpad and pretty hard to trigger the right-click menu I found this related issue #1 but it doesn't seem to be _entirely_ fixed.

**Comment by setzer22** [comment]
Thanks for reporting! A few questions:

- Do regular clicks work fine? If so, this is not the same as #1
- I'm not sure what you mean by the "roulette wheel" :thinking: does any other way of zooming work?
- Does the problem with zooming occur both on the viewport and the node graph?

**Comment by Kerollmops** [comment]
> * Do regular clicks work fine? If so, this is not the same as [Clicking things doesn't work. #1](https://github.com/setzer22/blackjack/issues/1)

Yup, regular clicks work fine!

> * I'm not sure what you mean by the "roulette wheel" 🤔 does any other way of zooming work?

Sorry, I mean mouse wheel i.e. two fingers on my trackpad.

> * Does the problem with zooming occur both on the 3d viewport and the node graph?

I am on the `feat/properties_inspector` branch and I am able to zoom on the graph _when I hover the 3d scene_ 😄
_You can compare this screenshot to https://github.com/setzer22/blackjack/issues/6#issuecomment-1025181653_

<img width="1680" alt="Capture d’écran 2022-01-30 à 17 51 49" src="https://user-images.githubusercontent.com/3610253/151709040-12c91834-59ff-469a-ad25-1de24ffd901a.png">

**Comment by Kerollmops** [comment]
> I am also unable to rotate or zoom on the 3d scene viewport.

I am, I just found out that I can control the 3d scene viewport only by hovering a small square top right, something like half of the actual viewport size. It seem like the visual viewports are not of the same size of the control viewports, something like half the size.

**Comment by setzer22** [comment]
Oh, I see what you mean! I was able to reproduce this by forcing a dpi factor of 2.0 on my end :+1:  I must be doing something wrong with the dpi when translating mouse events for the child viewports.

Let me see if I can get it sorted out :smile:

**Comment by setzer22** [comment]
I think it should be working now :tada: Can you verify on your end? Pulling b2ce067 should get you both a fix for this and #6

**Comment by Kerollmops** [comment]
That's indeed fixed, thank you! 🎉 

Just a small improvement would be to reduce the speed of the zoom speed, it is very difficult to be precise as it is very fast to zoom and unzoom.

**Comment by setzer22** [comment]
Cool! I'll close #6 and #7 then :)  I'll be tracking this zoom speed issue in #8
